[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#00FF41"
backgroundColor = "#050505"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#00FF41"
font = "monospace"
